[package]
name = "spark-providers"
version = "0.1.0"
edition = "2021"

[dependencies]
spark-types = { path = "../spark-types" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
nix = { workspace = true }
